name: Docker Image CI

on:
  push:
    branches: [ "off" ]

jobs:

  build:

    runs-on: ubuntu-latest
    env:
      CLOAK_VER: v2.10.0
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64,linux/386,linux/arm/v7
          file: ./Dockerfile
          push: true
          build-args: |
            CLOAK_VER=$CLOAK_VER
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/cloak:latest, ${{ secrets.DOCKERHUB_USERNAME }}/cloak:${{ env.CLOAK_VER }}
